hidden_layers:
  -
    - 50
    - 100
    - 50
  -
    - 20
    - 50
    - 20
  -
    - 30
    - 30
    - 30
    - 30
  -
    - 5
    - 10
    - 15
    - 20
    - 15
    - 10
    - 5
activation:
  - logistic
  - tanh
  - relu
alpha:
  - 0.0001
  - 0.001
  - 0.01