colsample_bytree:
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1
learning_rate:
  - 0.001
  - 0.01
  - 0.1
  - 1
max_depth:
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
objective:
  - reg:squarederror
subsample:
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1
num_boost_round:
  - 50
  - 100
  - 150
  - 200