name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          sudo docker compose build

      - name: Shut down existing containers
        run: |
          sudo docker compose down

      - name: Start the dashboard app
        run: |
          sudo docker compose up
